sonar.projectKey=Notes-Galore
sonar.projectName=Notes Galore
sonar.host.url=http://localhost:9000

# Source Locations
sonar.sources=frontend/src, backend/
# Exclusions
sonar.exclusions=**/node_modules/**, **/*.test.jsx, **/*.test.js, **/setupTests.js, **/setup.js, **/coverage/**, **/.nyc_output/**
# Coverage Report Paths
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info, backend/coverage/lcov.info